package com.elte.osz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.Arrays;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity(name = "Room")
@Table(name = "Room")

public class Room implements Serializable {

    @Column(nullable = false)
    @Basic
    private String name;
 @Override    
    public boolean equals(Object other){       
        
        if ( other == this )
           return true;
        
       Field[] thisFields= this.getClass().getDeclaredFields();
       Field[] objectFields= other.getClass().getDeclaredFields();
        //System.out.println(this.getClass().getName() + " - " + other.getClass().getName());
       return Arrays.deepEquals(thisFields, objectFields);
              
    }
    @Column(updatable = false, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    @Basic
    private int capacity;

    public Room() {

    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCapacity() {
        return this.capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
}
