package com.elte.osz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import com.elte.osz.logic.dbhandler.BaseEntity;
import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.IdClass;
import javax.persistence.OneToMany;

@Entity
public class Semester extends BaseEntity implements Serializable {

    @Column(columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP", updatable = false, insertable = true, nullable = false)
    @Basic
    private Timestamp created;

    @Column(nullable = false)
    @Basic    
    private String name;

    @OneToMany(cascade = {CascadeType.ALL}, targetEntity = SemesterItem.class)
    private List<SemesterItem> items;

    public Semester() {

    }

    public Timestamp getCreated() {
        return this.created;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<SemesterItem> getItems() {
        return this.items;
    }

    public void setItems(List<SemesterItem> items) {
        this.items = items;
    }
}
