package com.elte.osz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import com.elte.osz.logic.Department;
import com.elte.osz.logic.dbhandler.AbstractEntity;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

@Entity
public class Subject extends AbstractEntity implements Serializable {

    @Column(nullable = false)
    @Basic
    private String code;

    @Column(nullable = false)
    @Basic
    private String name;

    
    @Basic
    private byte semester;

    @Basic
    private byte hours_practical;

    @Basic
    private byte hours_nightly;

    @Column(nullable = false)
    @Basic
    @Enumerated(EnumType.STRING)
    private Department department;

    @Basic
    private byte hours_presentation;

    @Basic
    private String subjectType;

    public Subject(){
        super();
    }
    
    public Subject(String name, String code) {
       super();
       this.code = code;
       this.name = name;       
    }
    
    public Subject(
            String name, String code, int semester,
            int hours_presentation, int hours_practical, int hours_nightly,
            String subjectType, Department department
    ){
        super();
        this.code = code;
        this.name = name;
        this.semester = (byte) semester;
        this.hours_nightly = (byte) this.hours_nightly;
        this.hours_presentation = (byte) this.hours_presentation;
        this.hours_practical = (byte) this.hours_practical;
        this.subjectType = subjectType;
        this.department = department; 
        
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getSemester() {
        return this.semester;
    }

    public void setSemester(int semester) {
        this.semester = (byte) semester;
    }

    public int getHours_practical() {
        return this.hours_practical;
    }

    public void setHours_practical(int hours_practical) {
        this.hours_practical = (byte) hours_practical;
    }

    public int getHours_nightly() {
        return this.hours_nightly;
    }

    public void setHours_nightly( int hours_nightly) {
        this.hours_nightly =  (byte) hours_nightly;
    }

    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public int getHours_presentation() {
        return this.hours_presentation;
    }

    public void setHours_presentation(int hours_presentation) {
        this.hours_presentation = (byte) hours_presentation;
    }

    public String getSubjectType() {
        return this.subjectType;
    }

    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType;
    }
}
