package com.elte.osz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

@Entity

public class SyllabusItem implements Serializable {

    
    @OneToOne(optional = false, targetEntity = Subject.class)
    private Subject subject;

    
    @OneToOne(targetEntity = RoomGroup.class)
    private RoomGroup roomGroup;

    @Basic
    private int semester;

    @Column(updatable = false, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    
    @OneToOne(targetEntity = Room.class)
    private Room room;

    @OneToMany(targetEntity = Subject.class)
    private List<Subject> dependencies;

    public SyllabusItem() {

    }

    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public RoomGroup getRoomGroup() {
        return this.roomGroup;
    }

    public void setRoomGroup(RoomGroup roomGroup) {
        this.roomGroup = roomGroup;
    }

    public int getSemester() {
        return this.semester;
    }

    public void setSemester(int semester) {
        this.semester = semester;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Room getRoom() {
        return this.room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public List<Subject> getDependencies() {
        return this.dependencies;
    }

    public void setDependencies(List<Subject> dependencies) {
        this.dependencies = dependencies;
    }
}
