package com.elte.osz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import com.elte.osz.logic.dbhandler.AbstractEntity;
import java.io.Serializable;
import java.sql.Timestamp;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity
public class TimetableItem extends AbstractEntity implements Serializable {

    //@Id
    @OneToOne(targetEntity = Teacher.class)
    private Teacher teacher;

    //@Id
    @OneToOne(optional = false, targetEntity = Subject.class)
    private Subject subject;

    @Column(nullable = false)
    @Basic
    private Timestamp startTime;

    @Column(nullable = false)
    @Basic
    private Timestamp endTime;

    //@Id
    @OneToOne(optional = false, targetEntity = Room.class)
    private Room room;

    public TimetableItem() {
        super();
    }

    public Teacher getTeacher() {
        return this.teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public Timestamp getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    public Timestamp getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }

    public Room getRoom() {
        return this.room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }
}
