package com.elte.osz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import com.elte.osz.logic.dbhandler.BaseEntity;
import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

@Entity
public class Timetable extends BaseEntity implements Serializable {

    @Column(columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP", updatable = false, insertable = true, nullable = false)
    @Basic
    private Timestamp created;

    @OneToMany(targetEntity = SemesterItem.class)
    private List<SemesterItem> classes;

    @Column(nullable = false)
    @Basic
    private String name;

    public Timetable() {

    }

    public Timestamp getCreated() {
        return this.created;
    }
    public List<SemesterItem> getClasses() {
        return this.classes;
    }

    public void setClasses(List<SemesterItem> classes) {
        this.classes = classes;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
