package com.elte.tosz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

@Entity

public class ProposedTime extends IEntity implements Serializable {

    
    @OneToOne(targetEntity = Syllabus.class)
    private Syllabus syllabus;

    @Basic
    private Timestamp dtCreated;

    @OneToMany(targetEntity = ProposedTimeItem.class)
    private List<ProposedTimeItem> items;

    public ProposedTime() {

    }

    public Syllabus getSyllabus() {
        return this.syllabus;
    }

    public void setSyllabus(Syllabus syllabus) {
        this.syllabus = syllabus;
    }

    public Timestamp getDtCreated() {
        return this.dtCreated;
    }

    public void setDtCreated(Timestamp dtCreated) {
        this.dtCreated = dtCreated;
    }

    public List<ProposedTimeItem> getItems() {
        return this.items;
    }

    public void setItems(List<ProposedTimeItem> items) {
        this.items = items;
    }
}
