package com.elte.tosz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity

public class ProposedTimeItem extends IEntity implements Serializable {

    @Column(nullable = false)
    @Basic
    private int hour;

    @Column(nullable = false)
    @Basic
    private int len;

    @Column(nullable = false)
    @Basic
    private int day;

    
    @OneToOne(targetEntity = Room.class)
    private Room room;

    public ProposedTimeItem() {

    }

    public int getHour() {
        return this.hour;
    }

    public void setHour(int hour) {
        this.hour = hour;
    }

    public int getLen() {
        return this.len;
    }

    public void setLen(int len) {
        this.len = len;
    }

    public int getDay() {
        return this.day;
    }

    public void setDay(int day) {
        this.day = day;
    }

    public Room getRoom() {
        return this.room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }
}
