package com.elte.tosz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;

@Entity

public class Subject extends IEntity implements Serializable {

    @Column(nullable = false)
    @Basic
    private int maxTimeCount;

    @Basic
    private String code;

    @Column(nullable = false)
    @Basic
    private int estMemberCount;

    @Basic
    private String name;

    @Column(nullable = false)
    @Basic
    private float estMemberRatio;

    public Subject() {

    }

    public int getMaxTimeCount() {
        return this.maxTimeCount;
    }

    public void setMaxTimeCount(int maxTimeCount) {
        this.maxTimeCount = maxTimeCount;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public int getEstMemberCount() {
        return this.estMemberCount;
    }

    public void setEstMemberCount(int estMemberCount) {
        this.estMemberCount = estMemberCount;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public float getEstMemberRatio() {
        return this.estMemberRatio;
    }

    public void setEstMemberRatio(float estMemberRatio) {
        this.estMemberRatio = estMemberRatio;
    }
}
