package com.elte.tosz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

@Entity

public class Syllabus extends IEntity implements Serializable {

    @Column(unique = true, nullable = false)
    @Basic
    private String name;

    @OneToMany(targetEntity = SyllabusItem.class)
    private List<SyllabusItem> items;

    public Syllabus() {

    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<SyllabusItem> getItems() {
        return this.items;
    }

    public void setItems(List<SyllabusItem> items) {
        this.items = items;
    }
}
