package com.elte.tosz.logic.entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

@Entity

public class SyllabusItem extends IEntity implements Serializable {

    
    @OneToOne(optional = false, targetEntity = Subject.class)
    private Subject subject;

    @OneToMany(targetEntity = Subject.class)
    private List<Subject> dependencies;

    public SyllabusItem() {

    }

    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public List<Subject> getDependencies() {
        return this.dependencies;
    }

    public void setDependencies(List<Subject> dependencies) {
        this.dependencies = dependencies;
    }
}
