/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elte.osz.gui;

import com.elte.osz.logic.*;
import com.elte.osz.logic.controllers.RoomJpaController;
import com.elte.osz.logic.controllers.SemesterItemJpaController;
import com.elte.osz.logic.controllers.SemesterJpaController;
import com.elte.osz.logic.controllers.SubjectJpaController;
import com.elte.osz.logic.controllers.TeacherJpaController;
import com.elte.osz.logic.entities.SemesterItem;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author gabor
 */
public class MainWindow extends javax.swing.JFrame {

    Osz osz;
    private SemesterJpaController sc;
    private SemesterItemJpaController sic;
    private SubjectJpaController subjc;
    private TeacherJpaController tc;
    private RoomJpaController rc;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        osz = new Osz();
        sc = osz.getDataSet().getCtrlSemester();
        sic = osz.getDataSet().getCtrlSemesterItem();
        subjc = osz.getDataSet().getCtrlSubject();
        tc = osz.getDataSet().getCtrlTeacher();
        rc = osz.getDataSet().getCtrlRoom();
        initComponents();
        Orarend.setValueAt("08:00-10:00", 0, 0);
        Orarend.setValueAt("10:00-12:00", 1, 0);
        Orarend.setValueAt("12:00-14:00", 2, 0);
        Orarend.setValueAt("14:00-16:00", 3, 0);
        Orarend.setValueAt("16:00-18:00", 4, 0);
        Orarend.setValueAt("18:00-20:00", 5, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Orarend = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Órarend tervező");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(640, 555));

        Orarend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Hétfő", "Kedd", "Szerda", "Csütörtök", "Péntek"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Orarend.setCellSelectionEnabled(true);
        Orarend.setDoubleBuffered(true);
        Orarend.setFillsViewportHeight(true);
        Orarend.setPreferredSize(new java.awt.Dimension(0, 0));
        Orarend.setRowHeight(75);
        Orarend.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Orarend);
        if (Orarend.getColumnModel().getColumnCount() > 0) {
            Orarend.getColumnModel().getColumn(0).setResizable(false);
            Orarend.getColumnModel().getColumn(0).setPreferredWidth(50);
            Orarend.getColumnModel().getColumn(1).setResizable(false);
            Orarend.getColumnModel().getColumn(2).setResizable(false);
            Orarend.getColumnModel().getColumn(3).setResizable(false);
            Orarend.getColumnModel().getColumn(4).setResizable(false);
            Orarend.getColumnModel().getColumn(5).setResizable(false);
        }

        btnSearch.setText("Keresés");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        jComboBox1.setModel(new DefaultComboBoxModel(sc.findSemesterEntities().toArray()));

        jButton1.setText("Törlés");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        //manuálisan adtam hozzá listaelemet bemutatás miatt
        List<SemesterItem> sis = new ArrayList()
        {{
            add(new SemesterItem()
            {{              
                setId((long)25966);
                setEndTime("12:00");
                setStartTime("10:00");
                setDay("Szerda");
                setSubject(subjc.findSubject((long)1307));
                setRoom(rc.findRoom((long)56));
            }});
        }};
        PopupWindow popupFrame = new PopupWindow(this, true, sis);
        SemesterItem si = popupFrame.showDialog();
        String day = si.getDay();
        String from = si.getStartTime();
        int columnIndex = 0;
        int rowIndexFrom = 0;
        switch(day)
        {
            case "Hétfo": columnIndex = 1; break;
            case "Kedd": columnIndex = 2; break;
            case "Szerda": columnIndex = 3; break;
            case "Csütörtök": columnIndex = 4; break;
            case "Péntek": columnIndex = 5; break;    
        }
        switch(from)
        {
            case "10:00": rowIndexFrom = 1; break;
            case "12:00": rowIndexFrom = 2; break;
            case "14:00": rowIndexFrom = 3; break;
            case "16:00": rowIndexFrom = 4; break;
            case "18:00": rowIndexFrom = 5; break;
        }
        Orarend.getModel().setValueAt(si.getSubject().getName(), rowIndexFrom, columnIndex);
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnDeleteClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteClicked
        // TODO add your handling code here:
        if(Orarend.getSelectedColumn() != 0){
            Orarend.getModel().setValueAt(null, Orarend.getSelectedRow(), Orarend.getSelectedColumn());
        }
    }//GEN-LAST:event_btnDeleteClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow mw = new MainWindow();
                mw.setLocationRelativeTo(null);
                mw.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Orarend;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
